apiVersion: v1
kind: ConfigMap
metadata:
  name: ich-bin-eine-source-map
  namespace: default
  annotations:
      replik8or.c0deltin.io/reflection-allowed: "true"
data:
  harry: "potter"
  markus: "flint"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-source-map
  namespace: test-hogwarts
  annotations:
    replik8or.c0deltin.io/reflection-allowed: "true"
    replik8or.c0deltin.io/allowed-namespaces: "test-ravenclaw,test-hufflepuff,test-hogwarts"
data:
  foo: "bar"
  awdasdasd: "asdasdasd"