apiVersion: v1
kind: Namespace
metadata:
  name: test-hogwarts
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-gryffindor
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-hufflepuff
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-slytherin
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ravenclaw
