apiVersion: v1
kind: Secret
metadata:
  name: top-secret
  namespace: default
  annotations:
    replik8or.c0deltin.io/reflection-allowed: "true"
    replik8or.c0deltin.io/allowed-namespaces: "test-ravenclaw,test-hufflepuff,test-hogwarts"
stringData:
  foo: "bar"
  awdasdasd: "asdasdasd"
